<?php

/**
 * Provide a public area view for questions to answers for the support-chat
 *
 * @link       http://www.weedesign.de/weebotLite.html
 * @since      1.0.0
 *
 * @package    weebotLite
 * @subpackage weebotLite/public/template
 */
 
?>
<div class="answer type-question question" data-parent="<?php echo $parameter["question"]; ?>" id="<?php echo $this->plugin_name."_".$parameter["question"]; ?>_answer">
	<div class="message"><?php echo esc_html($parameter["answer"]->action); ?></div>
</div>