<?php

/**
 * Provide a admin area view for the "questions"-page of the plugin
 *
 * @link       http://www.weedesign.de/weebotLite.html
 * @since      1.0.0
 *
 * @package    weebotLite
 * @subpackage weebotLite/admin/template
 */
 
?>

<div class="wrap">

	<h1 class="wp-heading-inline"><?php echo esc_html( get_admin_page_title() ); ?></h1>
	
	<hr class="wp-header-end">
	
	<?php 
		
		/* 
		*	if something was posted
		*/
		if(isset($_GET["post"])) { 
		
			/* 
			*	if an action is defined
			*/
			if(isset($_GET["action"])) {
				switch($_GET["action"]) {
				
					/* 
					*	delete the question
					*/
					case "delete":
						$delete = $this->delete("questions",$_GET["post"]);
						$this->template("chat/question/delete");
					break;
					
					/* 
					*	view the question
					*/
					case "view":
						$this->template("chat/question/view");
					break;
					
				}
			}
		} else {

			/* 
			*	get a list of all questions
			*/
			$questions = $this->get_page_data("questions","answered!=1","question","question");
			
			?>
	
				<ul class="subsubsub">
					<li class="all"><a href="?page=<?php echo $_GET["page"]; ?>"<?php if(!isset($_GET["method"])&&$questions["search"]===false) { ?> class="current"<?php } ?>><?php esc_attr_e( 'All', $this->plugin_name ); ?> <span class="count">(<?php echo number_format($questions["all_count_real"],0,".","."); ?>)</span></a> |</li>
					<li class="publish"><a href="?page=<?php echo $_GET["page"]; ?>&amp;method=unanswered"<?php if(isset($_GET["method"])) { ?> class="current"<?php } ?>><?php esc_attr_e( 'Unanswered', $this->plugin_name ); ?> <span class="count">(<?php echo number_format($questions["all_count_special"],0,".","."); ?>)</span></a></li>
					<?php
						if($questions["search"]!==false) {
							?><li>| <a href="?page=<?php echo $_GET["page"]; ?>&amp;s=<?php echo $questions["s"]; ?>" class="current"><?php echo $questions["s"]; ?> <span class="count">(<?php echo number_format($questions["all_count_search"],0,".","."); ?>)</span></a></li><?php
						}
					?>
				</ul>
				
				<hr class="wp-header-end">
				
				<form action="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>" method="post" id="questionsForm">

					<p class="search-box">
						<label class="screen-reader-text" for="post-search-input"><?php esc_attr_e( 'Search Questions', $this->plugin_name ); ?>:</label>
						<input type="search" id="post-search-input" name="s" value="">
						<input type="submit" id="search-submit" class="button" value="<?php esc_attr_e( 'Search Questions', $this->plugin_name ); ?>">
					</p>
				
					<?php
					
						if($questions["start"]>$questions["all_count"]) {
							
							?><script type="text/javascript">document.location="?page=<?php echo $_GET["page"]; ?>";</script><?php
							
						} else {
						
							if(count($questions["questions"])>0) {
							
								?>
								
									<div class="tablenav top">
										<div class="alignleft actions bulkactions">
											<label for="bulk-action-selector-top" class="screen-reader-text"><?php esc_attr_e( 'Select bulk action', $this->plugin_name ); ?></label>
											<select name="action[]" id="bulk-action-selector-top">
												<option value="-1"><?php esc_attr_e( 'Bulk Actions', $this->plugin_name ); ?></option>
												<option value="trash"><?php esc_attr_e( 'Delete', $this->plugin_name ); ?></option>
											</select>
											<input type="submit" class="button" value="<?php esc_attr_e( 'Apply', $this->plugin_name ); ?>">
										</div>
										<div class="tablenav-pages">
											<span class="displaying-num"><?php echo number_format($questions["all_count"],0,".","."); ?> <?php esc_attr_e( 'questions', $this->plugin_name ); ?></span>
											<span class="pagination-links">
											<?php 
												if(isset($_GET["start"])) { 
													if($questions["page"]>2) {
														?><a class="tablenav-pages-navspan" href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">«</a><?php
													}
													?><a class="tablenav-pages-navspan" href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; if(ceil($questions["limit"]*($questions["page"]-1))-$questions["limit"]!=0) { echo '&amp;start='.(ceil($questions["limit"]*($questions["page"]-1))-$questions["limit"]); } if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">‹</a><?php
												}
											?>
											<span class="screen-reader-text"><?php esc_attr_e( 'Current Page', $this->plugin_name ); ?></span>
											<span id="table-paging" class="paging-input">
												<span class="tablenav-paging-text"><?php echo number_format(ceil($questions["page"]),0,".","."); ?> <?php esc_attr_e( 'of', $this->plugin_name ); ?> <span class="total-pages"><?php echo number_format(ceil($questions["all_count"]/$questions["limit"]),0,".","."); ?></span></span>
											</span>
											<?php 
												if($questions["all_count"]/$questions["limit"]>1) { 
													if($questions["page"]<$questions["all_count"]/$questions["limit"]) {
														?>
															<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; ?>&amp;start=<?php echo $questions["limit"]*($questions["page"]);  if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>" class="tablenav-pages-navspan">›</a>
															<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; ?>&amp;start=<?php echo (ceil($questions["all_count"]/$questions["limit"])*$questions["limit"])-$questions["limit"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>" class="tablenav-pages-navspan">»</a>
														<?php
													}
												}
											?>
											</span>
										</div>
										<br class="clear">
									</div>
							
									<table class="wp-list-table widefat fixed striped pages">
										
										<thead>
											<tr>
												<td id="cb" class="manage-column column-cb check-column">
													<label class="screen-reader-text" for="cb-select-all-1"><?php esc_attr_e( 'Select All', $this->plugin_name ); ?></label>
													<input id="cb-select-all-1" type="checkbox">
												</td>
												<th scope="col" id="title" class="manage-column column-title column-primary sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=title&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
														<span><?php esc_attr_e( 'Title', $this->plugin_name ); ?></span>
														<span class="sorting-indicator"></span>
													</a>
												</th>
												<th scope="col" id="page" class="manage-column column-page column-primary column-title sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=page&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
														<span><?php esc_attr_e( 'Page', $this->plugin_name ); ?></span>
														<span class="sorting-indicator"></span>
													</a>
												</th>
												<th scope="col" id="author" class="manage-column column-author"><?php esc_attr_e( 'Author', $this->plugin_name ); ?></th>
												<th scope="col" id="date" class="manage-column column-date sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=date&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
														<span><?php esc_attr_e( 'Date', $this->plugin_name ); ?></span>
														<span class="sorting-indicator"></span>
													</a>
												</th>
											</tr>
										</thead>

										<tbody id="the-list">
						
										<?php
								
										for($i=0;$i<$questions["limit"];$i++){
											if(isset($questions["questions"][$i])) {
												
												?>
												
													<tr id="post-<?php echo $questions["questions"][$i]->id; ?>" class="iview author-self level-0 post-<?php echo $questions["questions"][$i]->id; ?> type-page status-publish hentry">
														<th scope="row" class="check-column">
															<label class="screen-reader-text" for="cb-select-<?php echo $questions["questions"][$i]->id; ?>"><?php esc_attr_e( 'Select', $this->plugin_name ); ?></label>
															<input id="cb-select-<?php echo $questions["questions"][$i]->id; ?>" type="checkbox" name="question[]" value="<?php echo $questions["questions"][$i]->id; ?>">
														</th>
														<td class="title column-title has-row-actions column-primary page-title" data-colname="Title">
															<strong>
																<?php 
																	if(!empty($questions["questions"][$i]->question)) {
																		?><a class="row-title" href="?page=<?php echo $_GET["page"]; ?>&amp;post=<?php echo $questions["questions"][$i]->id; ?>&amp;action=view" aria-label="View"><?php
																			echo esc_html($questions["questions"][$i]->question);
																		?></a><?php
																	}
																	if(!empty($questions["questions"][$i]->files)) {
																		$this->template("chat/question/question/files",array("ids"=>$questions["questions"][$i]->files));
																	}
																	if(!empty($questions["questions"][$i]->screenshot)) {
																		$this->template("chat/question/question/screenshot",array("id"=>$questions["questions"][$i]->screenshot));
																	}
																?>
															</strong>
															<div class="row-actions">
																<span class="view">
																	<a href="?page=<?php echo $_GET["page"]; ?>&amp;post=<?php echo $questions["questions"][$i]->id; ?>&amp;action=view" aria-label="View"><?php esc_attr_e( 'View', $this->plugin_name ); ?></a>
																	|
																</span>
																<span class="trash">
																	<a href="?page=<?php echo $_GET["page"]; ?>&amp;post=<?php echo $questions["questions"][$i]->id; ?>&amp;action=delete" data-id="<?php echo $questions["questions"][$i]->id; ?>" class="weebotLite-delete" data-table="questions" aria-label="Move “Sample Page” to the Trash"><?php esc_attr_e( 'Trash', $this->plugin_name ); ?></a>
																	|
																</span>
																<span class="view">
																	<?php
																		$answer = $this->get_answer_by_question($questions["questions"][$i]->id);
																		if($answer!==false) {
																			?><a href="?page=<?php echo $this->plugin_name; ?>-answers&amp;post=<?php echo $answer[0]->id; ?>&amp;action=edit" aria-label="Answer"><?php esc_attr_e( 'Edit Answer', $this->plugin_name ); ?></a><?php
																		} else {
																			?><a href="?page=<?php echo $this->plugin_name; ?>-answers&amp;post=<?php echo $questions["questions"][$i]->id; ?>&amp;action=create" aria-label="Answer"><?php esc_attr_e( 'Create Answer', $this->plugin_name ); ?></a><?php
																		}
																	?>
																</span>
															</div>
														</td>
														<td class="page url column-page column-primary column-title" data-colname="Page">
															<?php 
																$page = $this->get_page_by("id",$questions["questions"][$i]->page);
																echo $page->page; 
															?>
														</td>
														<?php
															$question_user = $this->get_user($questions["questions"][$i]->user);
														?>
														<td class="author column-author" data-colname="Author">
															<a href="<?php echo admin_url( 'admin.php?page=' . $this->plugin_name . '-user' ); ?>&amp;post=<?php echo $question_user->id; ?>">
															<?php 
																if($question_user->user==-1) {
																	if(!empty($question_user->name)) {
																		echo esc_html($question_user->name);
																	} else {
																		esc_attr_e( 'anonym', $this->plugin_name );
																	}
																} else {
																	if ($question_user_data = get_userdata($question_user->user)) {
																		echo $question_user_data->data->display_name;
																	} else {
																		esc_attr_e( 'anonym', $this->plugin_name );
																	}
																}
															?></a>
														</td>
														<td class="date column-date" data-colname="Date"><abbr title="<?php echo $questions["questions"][$i]->time; ?>"><?php $timeArr = explode(" ",$questions["questions"][$i]->time); echo $timeArr[0]; ?></abbr></td>
													</tr>
												
												<?php
												
											}
										}
								
										?>
								
										</tbody>
										<tfoot>
											<tr>
												<td class="manage-column column-cb check-column">
													<label class="screen-reader-text" for="cb-select-all-2"><?php esc_attr_e( 'Select All', $this->plugin_name ); ?></label>
													<input id="cb-select-all-2" type="checkbox">
												</td>
												<th scope="col" class="manage-column column-title column-primary sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=title&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
														<span><?php esc_attr_e( 'Title', $this->plugin_name ); ?></span>
														<span class="sorting-indicator"></span>
													</a>
												</th>
												<th scope="col" id="page" class="manage-column column-page column-primary column-title sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=page&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
														<span><?php esc_attr_e( 'Page', $this->plugin_name ); ?></span>
														<span class="sorting-indicator"></span>
													</a>
												</th>
												<th scope="col" class="manage-column column-author"><?php esc_attr_e( 'Author', $this->plugin_name ); ?></th>
												<th scope="col" class="manage-column column-date sortable <?php echo $questions["orderAnti"]; ?>">
													<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=date&amp;order=<?php echo $questions["orderAnti"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">
													<span><?php esc_attr_e( 'Date', $this->plugin_name ); ?></span>
													<span class="sorting-indicator"></span>
													</a>
												</th>
											</tr>
										</tfoot>

									</table>
									
									<div class="tablenav bottom">
										<div class="alignleft actions bulkactions">
											<label for="bulk-action-selector-bottom" class="screen-reader-text"><?php esc_attr_e( 'Select bulk action', $this->plugin_name ); ?></label>
											<select name="action[]" id="bulk-action-selector-bottom">
												<option value="-1"><?php esc_attr_e( 'Bulk Actions', $this->plugin_name ); ?></option>
												<option value="trash"><?php esc_attr_e( 'Delete', $this->plugin_name ); ?></option>
											</select>
											<input type="submit" class="button" value="<?php esc_attr_e( 'Apply', $this->plugin_name ); ?>">
										</div>
										<div class="tablenav-pages">
											<span class="displaying-num"><?php echo number_format($questions["all_count"],0,".","."); ?> <?php esc_attr_e( 'questions', $this->plugin_name ); ?></span>
											<span class="pagination-links">
											<?php 
												if(isset($_GET["start"])) { 
													if($questions["page"]>2) {
														?><a class="tablenav-pages-navspan" href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">«</a><?php
													}
													?><a class="tablenav-pages-navspan" href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; if(ceil($questions["limit"]*($questions["page"]-1))-$questions["limit"]!=0) { echo '&amp;start='.(ceil($questions["limit"]*($questions["page"]-1))-$questions["limit"]); } if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>">‹</a><?php
												}
											?>
											<span class="screen-reader-text"><?php esc_attr_e( 'Current page', $this->plugin_name ); ?></span>
											<span id="table-paging" class="paging-input">
												<span class="tablenav-paging-text"><?php echo number_format(ceil($questions["page"]),0,".","."); ?> of <span class="total-pages"><?php echo number_format(ceil($questions["all_count"]/$questions["limit"]),0,".","."); ?></span></span>
											</span>
											<?php 
												if($questions["all_count"]/$questions["limit"]>1) { 
													if($questions["page"]<$questions["all_count"]/$questions["limit"]) {
														?>
															<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; ?>&amp;start=<?php echo $questions["limit"]*($questions["page"]);  if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>" class="tablenav-pages-navspan">›</a>
															<a href="?page=<?php echo $_GET["page"]; ?>&amp;orderby=<?php echo $questions["orderby"]; ?>&amp;order=<?php echo $questions["order"]; ?>&amp;start=<?php echo (ceil($questions["all_count"]/$questions["limit"])*$questions["limit"])-$questions["limit"]; if(isset($_GET["method"])) { ?>&amp;method=unanswered<?php } if($questions["search"]!==false) { ?>&amp;s=<?php echo $questions["s"]; } ?>" class="tablenav-pages-navspan">»</a>
														<?php
													}
												}
											?>
											</span>
										</div>
										<br class="clear">
									</div>
								
								<?php
							}
						
						}
						
					?>
				
				</form>
				
			<?php 
		} 
	?>

</div>
