<?php

/**
 * Provide a admin view for the "delete"-action for questions
 *
 * @link       http://www.weedesign.de/weebotLite.html
 * @since      1.0.0
 *
 * @package    weebotLite
 * @subpackage weebotLite/admin/template
 */
 
?>
<div id="setting-error-settings_updated" class="updated settings-error notice is-dismissible"> 
	<p><strong><?php esc_attr_e( 'Question deleted', $this->plugin_name ); ?></strong></p>
	<button type="button" class="notice-dismiss"><span class="screen-reader-text"><?php esc_attr_e( 'Dismiss this notice', $this->plugin_name ); ?>.</span></button>
</div>
<script type="text/javascript">document.location="?page=<?php echo $_GET["page"]; ?>";</script>